---
- name: install zabbix repository
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/{{ ansible_distribution|lower }}/pool/main/z/zabbix-release/zabbix-release_latest%2B{{ ansible_distribution|lower }}{{ ansible_distribution_version }}_all.deb"

- name: install packages
  apt:
    name:
      - zabbix-agent
    state: latest
    update_cache: yes

- name: put config files
  template:
    src: "{{ item }}"
    dest: "{{ item | regex_replace('^.*\\.\\./templates','') | regex_replace('\\.j2$','') }}"
  with_fileglob:
    - ../templates/etc/zabbix/zabbix_agentd.d/*.j2
  notify: restart zabbix-agent
