---
- name: get ubuntu version
  shell: lsb_release -r -s
  register: result
  changed_when: False

- name: install zabbix repository
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu{{ result.stdout }}_all.deb"

- name: install packages
  apt:
    name:
      - zabbix-agent
    update_cache: yes

- name: put config files
  template:
    src: "{{ item }}"
    dest: "{{ item | regex_replace('^.*\\.\\./templates','') | regex_replace('\\.j2$','') }}"
  with_fileglob:
    - ../templates/etc/zabbix/zabbix_agentd.d/*.j2
  notify: restart zabbix-agent
