---
- name: check os version
  fail: msg='OS is NOT Ubuntu (>= 20.x)'
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 20)

- name: update ca-certificates
  apt:
    name: ca-certificates
    state: latest
    update_cache: yes
